In [1]:
#импорт библиотеки
import numpy as np

In [2]:
#массив из 10 нулей
zer=np.zeros(10)
print(zer)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#массив из 10 единиц
one=np.ones(10)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
#массив из 10 пятерок
five=np.ones(10)*5
print(five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [5]:
#массив из целых чисел от 10 до 50
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
#массив из четных чисел от 10 до 50
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [7]:
#матрица 3*3 из чисел от 0 до 8
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#единичная матрица 3*3
mat=np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#генерация случайного числа от 0 до 1
random=np.random.random()
print(random)

0.08152990218070455


In [10]:
#генерация массива из 25 случайных чисел стандартного нормального распределения
random=np.random.normal(0,1,25)
print(random)

[ 0.69351947 -2.0311609  -0.39864846 -0.58131709  0.20633992 -0.15534648
  0.47922283  0.09235367  1.36527936  1.13570038  1.50164197  1.1376043
 -0.27173838 -0.7963321  -1.60253919 -0.03447046 -1.64505892  0.0839239
 -0.69792636 -2.28517514  1.1154268   1.14012337  0.21130139 -1.79774581
  0.6705979 ]


In [11]:
#создать матрицу
mat=np.arange(0.01,1.01,0.01).reshape(10,10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [12]:
#стартовая матрица
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
#вывести матрицу
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [14]:
#вывести значение 20
print(mat[3:4,4:])

[[20]]


In [15]:
#вывести матрицу
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [16]:
#вывести матрицу
mat[4:]

array([[21, 22, 23, 24, 25]])

In [17]:
#вывести матрицу
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
#сумма всех значений
print(mat.sum())

325


In [19]:
#стандартное отклонение в матрице
print(mat.std())

7.211102550927978


In [20]:
#сумма значений в колонках
print(mat.sum(axis=0))

[55 60 65 70 75]
